## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##

coreo_aws_vpc_vpc "${CC-AWS-ELEM_VPC_NAME}" do
  action :find_or_create
  cidr "${CC-AWS-ELEM_VPC_OCTETS}/${CC-AWS-ELEM_VPC_MASK}"
  internet_gateway true
end

